services:
  - type: web
    name: portfoliomern
    env: node
    plan: free
    buildCommand: npm run render-postbuild
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        value: https://portfoliomern.onrender.com
    healthCheckPath: /api/health
